# Generated by Django 5.0.1 on 2024-01-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('disc', models.TextField()),
                ('image', models.ImageField(upload_to='team')),
            ],
        ),
    ]
