# Generated by Django 5.0.1 on 2024-01-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='disc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team',
        ),
    ]
