# Generated by Django 5.0.1 on 2024-01-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=25)),
                ('priority', models.IntegerField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='todoimage')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
